---

- pre_tasks:
  - name: Upgrade repositories. 
    apt: 
      upgrade: dist

  - name: configure interface
    net_interface:
      name: ge-0/0/1
      description: test-interface

  - name: make interface down
    net_interface:
      name: ge-0/0/1
      description: test-interface
      enabled: False

- name: Adding canonical repository
  apt_repository:
    repo: deb http://archive.canonical.com/ubuntu hardy partner
    state: present  

- name: Adding bionic epository
  apt_repository:
    repo: deb http://ppa.launchpad.net/pinta-maintainers/pinta-stable/ubuntu bionic main
    state: present  

- name: Adding system76 repository
  apt_repository:
    repo: deb http://ppa.launchpad.net/system76/pop/ubuntu bionic main
    state: present  

- name: Adding nordvpn repository
  apt_repository:
          deb: https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn-release_1.0.0_all.deb?_ga=2.169657185.1324022406.1543152122-1992471565.1543014877  

- name: Adding NVidia repository
  apt_repository:
    repo: deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1704/x86_64
    state: present  

- name: Adding google repository
  apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: present  

- name: Adding google repository
  apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: present  

- name: Configure the Oracle APT key
  apt_key: 
    url: https://www.virtualbox.org/download/oracle_vbox.asc 
    state: present

- name: Configure the VirtualBox APT repositories
  apt_repository: 
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib" 
    state: present

- name: Install VirtualBox 5.0
  apt: 
    pkg: virtualbox-5.0 
    state: present
    
- name: Adding TLP repo
  apt_repository:
    repo: 'ppa:linrunner/tlp'

- name: Adding Java repo
  apt_repository:
    repo: 'ppa:webupd8team/java'

- name: Adding Terminator repo
  apt_repository:
    repo: 'ppa:gnome-terminator'

- name: Adding Transmission repo
  apt_repository:
    repo: 'ppa:transmissionbt/ppa'

- name: Update repositories. 
  apt: 
    update_cache: yes

- name: Installing terminator. 
  apt: 
    name: terminator
    update_cache: yes

- name: Installing snap. 
  apt: 
    name: snapd
    update_cache: yes

- name: Installing tilda. 
  apt: 
    name: tilda
    update_cache: yes

- name: Installing powertop. 
  apt: 
    name: powertop
    update_cache: yes

- name: Installing screencast. 
  apt: 
    name: byzanz
    update_cache: yes

- name: Installing xclip. 
  apt: 
    name: xclip
    update_cache: yes

- name: Installing tlp
  apt:
    name: "{{ tlpGrp }}"
    update_cache: yes
    var:
      tlpGrp:
      - tlp 
      - tlp-rdw

- name: Installing transmission
  apt:
    name: "{{ transGrp }}"
    update_cache: yes
    var:
      transGrp:
      - transmission-cli 
      - transmission-common 
      - transmission-daemon 

