---

- name: Ubuntu bionic environment playbook
- hosts:
    - localhost
    - travis-ci
  remote_user: ansible
  become: true
  become_user: root
  become_method: sudo
  gather_facts: true
  roles:
    - { role: admin, become: true }
    - { role: devops, become: true }
    - { role: media, become: true }
    - { role: prog, become: true }
    - { role: cleanup, become: true }
