---

- hosts: all
  tasks:

  - name: "[ Programing ] - Installing flatpak type applications: Sublime Text, Visual Studio Code" 
    flatpak: 
       name: "{{item}}" 
       state: present
    with_items: 
    - com.sublimetext.three
    - com.visualstudio.code

  - name: "[ Programing ] - Installing apt type packages: Python 3, pip python-dev"
    apt: 
      name: [ 'python3-minimal', 'python-dev', 'python-pip' ]
      state: latest 
      update_cache: yes

  - name: "[ Programing ] - Installing pkg type packages: Java sbt"
    apt: 
    #pkg: [ 'oracle-java11-installer', 'sbt', 'oracle-java11-set-default'] -- Had problems with Java packages. Needed to do it manually 
      pkg: sbt 
      update_cache: yes

  - name: "[ Programing ] - Installing deb type packages: Scala" 
    apt: 
      deb: "{{item}}" 
      update_cache: yes
    with_items: 
    - http://scala-lang.org/files/archive/scala-2.12.1.deb
