---

- name: Install Sublime Text
  snap:
    name: sublime-text
    state: present  

- name: Install Visual Studio
  snap:
    name: intellij-idea-community
    state: present  

- name: Install Python packages
  apt: 
    name: "{{ pythonGrp }}"
    state: latest 
    update_cache: yes 
    var: 
      pythonGrp:
      - python
      - python-dev
      - python-pip

- name: Install Java
  apt:
    pkg: oracle-java8-set-default
    update_cache: yes 

- name: Install Scala.
  apt:
    deb: http://scala-lang.org/files/archive/scala-2.12.1.deb
 
