---
- hosts: pull_mode_hosts
  become : yes
  tasks:
    
    - name: "[ Media ] Install flatpak applications: Spotify, VLC, Gimp"
      flatpak:
        name:  "{{ item }}"
        state: present
      with_items:
      - com.spotify.Client
      - org.videolan.VLC
      - org.gimp.GIMP

    - name: "[ Media ] Install apt applications: Shutter"
      apt:
        name: ['shutter', 'mint-meta-codecs', 'snapd']
        state: present

    - name: "[ Media ] Install deb applications: Franz, Google Chrome"
      apt:
        deb: "{{ item }}"
        state: present
      with_items:
      - https://github.com/meetfranz/franz/releases/download/v5.0.1/franz_5.0.1_amd64.deb
      - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb  

    - name: "[ Media ] Remove Firefox"
      apt:
        pkg: firefox
        state: absent  
