- name: remove amazon launcher
  apt:
    name: ubuntu-web-launchers
    state: absent 
 
- name: Disable WebApps and other shitty integrations
  command: "{{ item }}"
  become: true
  become_user: "{{ ansible_env.USER }}"
  with_items:
    - gsettings set com.canonical.unity.webapps integration-allowed false
    - gsettings set com.canonical.Unity.Lenses disabled-scopes "['more_suggestions-amazon.scope', 'more_suggestions-u1ms.scope', 'more_suggestions-populartracks.scope', 'music-musicstore.scope', 'more_suggestions-ebay.scope', 'more_suggestions-ubuntushop.scope', 'more_suggestions-skimlinks.scope']"
    - gsettings set com.canonical.unity.webapps preauthorized-domains "[]"
    - gsettings set com.canonical.Unity.ApplicationsLens display-available-apps false

- name: Remove exemples shortcut
  file: path="{{ ansible_env.HOME }}/examples.desktop" force=yes state=absent

